// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zad10.Models;

namespace zad10.Migrations
{
    [DbContext(typeof(MainDbContext))]
    partial class MainDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("zad10.Models.Student", b =>
                {
                    b.Property<int>("IdStudent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdStudia")
                        .HasColumnType("int");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nazwisko")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NrIndeksu")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RokStudiow")
                        .HasColumnType("int");

                    b.HasKey("IdStudent");

                    b.HasIndex("IdStudia");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            IdStudent = 1,
                            IdStudia = 1,
                            Imie = "Marcin",
                            Nazwisko = "Rawa",
                            NrIndeksu = "11",
                            RokStudiow = 5
                        },
                        new
                        {
                            IdStudent = 2,
                            IdStudia = 1,
                            Imie = "Anna",
                            Nazwisko = "Tobiasz",
                            NrIndeksu = "12",
                            RokStudiow = 4
                        },
                        new
                        {
                            IdStudent = 3,
                            IdStudia = 2,
                            Imie = "Marcin",
                            Nazwisko = "Krasuski",
                            NrIndeksu = "13",
                            RokStudiow = 3
                        },
                        new
                        {
                            IdStudent = 4,
                            IdStudia = 3,
                            Imie = "Tomasz",
                            Nazwisko = "Sieciechowicz",
                            NrIndeksu = "14",
                            RokStudiow = 2
                        });
                });

            modelBuilder.Entity("zad10.Models.Studia", b =>
                {
                    b.Property<int>("IdStudia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Tryb")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdStudia");

                    b.ToTable("Studias");

                    b.HasData(
                        new
                        {
                            IdStudia = 1,
                            Nazwa = "Filozofia",
                            Tryb = "Dzienny"
                        },
                        new
                        {
                            IdStudia = 2,
                            Nazwa = "Ekonomia",
                            Tryb = "Dzienny"
                        },
                        new
                        {
                            IdStudia = 3,
                            Nazwa = "Informatyka",
                            Tryb = "Dzienny"
                        });
                });

            modelBuilder.Entity("zad10.Models.Student", b =>
                {
                    b.HasOne("zad10.Models.Studia", "Studia")
                        .WithMany("Students")
                        .HasForeignKey("IdStudia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Studia");
                });

            modelBuilder.Entity("zad10.Models.Studia", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
